### ISSUE TITLE
[Enhancement]: Freeze Controller in the Center

### ISSUE THREAD

**Issue by dortamur** [azuwis/zigbee2mqtt-networkmap#13]
**Describe the bug**
This is a Feature Request: 

Would it be possible to have an option to freeze the Controller in the center (vertically & horizontally) of the panel, or at least have it default to be centered at the start? 

I have 1 controller, 4 routers & 30ish devices, and the graph looks the cleanest & makes the most sense when I manually drag the Red controller node into the center.

**Comment by azuwis** [comment]
Please fill the issue template, provide screenshots and sensor states. I can't help without those information.

The coordinator should be automatically placed in the center in most cases. Without your sensor states, I can not replicate the behavior.

**Comment by azuwis** [comment]
Closing due to lack of response. Feel free to reopen if problem is not resolved.
