### ISSUE TITLE
Friendly_name instead device_id

### ISSUE THREAD

**Issue by netamego** [azuwis/zigbee2mqtt-networkmap#17]
Hi, 
In home assistant y can change the friendly name and the entity name but not device_name. Can i configure friendly_name or entety_name in your amazing card?. Your card works as expected but name showed is a serial number and it's difficult to know wich device belong to each serial number. 
Thanks a lot.
Best regards!!!

**Comment by azuwis** [comment]
The names showed in the map are given by Zigbee2mqtt, you can customize them, see https://www.zigbee2mqtt.io/configuration/device_specific_configuration.html for the friendly_name option.

In fact if you customize them in this way, HomeAssistant will automatically use the same names when mqtt auto discovery is enabled, which is true in most cases, see https://www.zigbee2mqtt.io/integration/home_assistant.html

**Comment by azuwis** [comment]
FAQ added to README. Closing due to lack of response. Feel free to reopen if problem is not resolved.
