### ISSUE TITLE
change the tag name of each entity

### ISSUE THREAD

**Issue by Shanghaiman** [azuwis/zigbee2mqtt-networkmap#19]
how did you do it?
all my entities show a long numbers and letters name.

can you explain step by step?
![zigbee2mqttmap](https://user-images.githubusercontent.com/47654029/72684530-3efb4880-3b1c-11ea-8fc8-049fa1846eab.jpg)

do you know why i dont see the link between some devices though they are connected 

thanks

**Comment by azuwis** [comment]
See FAQ https://github.com/azuwis/zigbee2mqtt-networkmap#faq for how to change device names.

For detached devices, see https://github.com/azuwis/zigbee2mqtt-networkmap/issues/14

**Comment by ministryofsillywalks** [comment]
So I also tried giving my zigbee devices friendly names however "devices" as described in the z2mqtt faq has been deprecated and doesn't work anymore afaik.
trying to add 
`devices: devices.yaml`
to my configuration.yaml gives me an error...
Where exactly did you add "friendly_name"?

**Comment by azuwis** [comment]
Closing due to lack of response. Feel free to reopen if problem is not resolved.

**Comment by d-edge82** [comment]
dear @azuwis 

I am having the same issue where I only see device ID's instead of names.

I see in the documentation that the friendly name should be available to be configured through the HA registry, and that I did.
and yet, I only see device ID's on the map.

![image](https://user-images.githubusercontent.com/60448083/81482675-8af40980-9241-11ea-8e72-14cb04ff7b14.png)


Please advise

**Comment by azuwis** [comment]
Do not use Home Assistant to change device name, it's to complicate (if possible) to get those information from Home Assistant.

Instead, change the name in Zigbee2mqtt, see FAQ.

Q: How can I customize device names in the map?

A: The names showed in the map are given by Zigbee2mqtt, you need to configure Zigbee2mqtt to customize them, see https://www.zigbee2mqtt.io/information/configuration.html for the friendly_name option.
