### ISSUE TITLE
Additional parameters and behavior.

### ISSUE THREAD

**Issue by zen2** [azuwis/zigbee2mqtt-networkmap#2]
Thanks a lot for this module that is really great !

I would like to be able to modify in lovelace configuration colors to easily integrate with different themes:
- coordinator color node
- router color node
- end-point color node
- links colors

In addition when you select a node in order to quickly view what is connected to this node it could be really usefull to change:
- color of links connected to selected node
- color of nodes connected to selected one
- font size or style like bold of selected node and connected ones

**Comment by azuwis** [comment]
You can config extra css styles and use css variables to theme on v0.5.0, see README.md.

For the 2nd part of the issue, I think it's a bit complicated. If you like to implement it, I'm open to pull requests.

**Comment by zen2** [comment]
Thanks for the CSS styles.
Is it possible to have a percent value relative to viewport height for 'height' parameter ?
Because right now it's almost impossible to use all space in panel mode on different devices (tablet, phone, desktop).

**Comment by azuwis** [comment]
Try:

``` yaml
    css: |
      .net {
        height: 85vh;
      }
```

**Comment by seventhsite** [comment]
Another request - how about icons/photo of the devices like in z2m map?

![image](https://user-images.githubusercontent.com/19604503/117667695-d0794880-b1ad-11eb-81ef-09f197eca270.png)
