### ISSUE TITLE
Feature request: coordinator in the middle

### ISSUE THREAD

**Issue by SaturnusDJ** [azuwis/zigbee2mqtt-networkmap#23]
Similar to https://github.com/azuwis/zigbee2mqtt-networkmap/issues/13, possibly.

First of all, nice work. Great integration with HA, a lot easier than external methods.

When the map is displayed, the coordinator probably is not in the middle. It is a bit challenging to see quickly how the network is build.

When placing the coordinator in the middle, surrounded by routers, this becomes a lot easier.

Example:
![x](https://user-images.githubusercontent.com/14320018/82377642-46782300-9a24-11ea-860f-fd12aa392d44.png)
Removed some text due to privacy.

Here you see the coordinator instantly, then you see the 'trees' expanding away from it.

**Comment by azuwis** [comment]
The high level library used is https://github.com/emiliorizzo/vue-d3-network, which does not export API to do force a node in the middle.

The low level library used is https://d3js.org/, which is possible to do this https://stackoverflow.com/questions/21843206/d3-force-layout-fix-root-node-at-the-center. But I don't see an easy way to integrate it into vue-d3-network.

**Comment by SaturnusDJ** [comment]
Thank you for the explanation. What would be a follow up step to try to get this sorted out?
