### ISSUE TITLE
Documentation update : path for hacsfile change

### ISSUE THREAD

**Issue by YoShiiro** [azuwis/zigbee2mqtt-networkmap#27]
Hello

first thanks for all the work done.

Is it possible to make a little change in the README.md at the [**Frontend setup (HACS)**](https://github.com/azuwis/zigbee2mqtt-networkmap/blob/master/README.md#frontend-setup-hacs)

replace : 
 `- url: /community_plugin/zigbee2mqtt-networkmap/zigbee2mqtt-networkmap.js`
by : 
 `- url: /hacsfile/zigbee2mqtt-networkmap/zigbee2mqtt-networkmap.js`

 Path change for Hacs file and i know it took me some minutes to find it :D so if it can help new people using it.

Thanks in advance.

**Comment by azuwis** [comment]
Thanks.

Document updates are welcome. You can edit README.md, and make pull requests.  In fact, the HACS part of the document was written by a contributor.
