### ISSUE TITLE
refresh graph when browser window is resized

### ISSUE THREAD

**Issue by zen2** [azuwis/zigbee2mqtt-networkmap#3]
Both on chrome and firefox, when you resize the browser window the graph is clipped on old window size.  The graph need to take in consideration the new size.

**Comment by azuwis** [comment]
I believe it's a vue-d3-network bug here https://github.com/emiliorizzo/vue-d3-network/blob/master/src/vue-d3-network.vue#L211-L212.

It does listen to window resize event, but once the height and width are set, they are not recalculated.

**Comment by zen2** [comment]
Thanks. works like a charm.
