### ISSUE TITLE
Feature Request : Overlay map and devices onto house plan?

### ISSUE THREAD

**Issue by TommySharpNZ** [azuwis/zigbee2mqtt-networkmap#33]
Is there any chance an option could be created to overlay the map onto a house plan and have some way to pin sensors and routers onto the house plan? This would GREATLY improve the readability and help identify issues?

**Comment by azuwis** [comment]
This is an interesting idea, but hard to implement (at least for me).

I don't think home-assistant lovelace card can be overlaid. You need to replace house plan card with a modified one to add custom functionality, which is out of scope of this project.
