### ISSUE TITLE
Missing some information on networkmap

### ISSUE THREAD

**Issue by Olive80** [azuwis/zigbee2mqtt-networkmap#39]
**Describe the bug**
Hello,
The map does not show me the arrows with the connections.
I am using a Sonoff Zigbee 3.0 USB Dongle Plus (CC2652P) coordinator on my Raspberry.

I also connected a cc2531 router to the electric power but not recognized

![Capture zigbee map](https://user-images.githubusercontent.com/58820544/194087079-c2abaeee-c33e-40f0-9097-0f2581993033.png)

****Home Assistant version****
Home Assistant 2022.9.7

Zigbee2mqtt version
Zigbee2mqtt to version 1.22.2

OS and browser version
  Debian 11

**State attributes of `sensor.zigbee2mqtt_networkmap`**
links: [ ]
nodes:
  - definition: null
    failed:
      - lqi
      - routingTable
    friendlyName: Coordinator
    ieeeAddr: '0x00124b0018e87194'
    lastSeen: 1664969656772
    networkAddress: 65035
    type: Coordinator
  - definition:
      description: Aqara vibration sensor
      model: DJT11LM
      supports: >-
        battery, vibration, action, strength, sensitivity, angle_x, angle_y,
        angle_z, voltage, linkquality
      vendor: Xiaomi
    friendlyName: vibration
    ieeeAddr: '0x00158d00032db12d'
    lastSeen: 1664972509355
    manufacturerName: LUMI
    modelID: lumi.vibration.aq1
    networkAddress: 21
    type: EndDevice
  - definition:
      description: MiJia temperature & humidity sensor
      model: WSDCGQ01LM
      supports: battery, temperature, humidity, voltage, linkquality
      vendor: Xiaomi
    friendlyName: maison
    ieeeAddr: '0x00158d00040670c2'
    lastSeen: 1664969458704
    manufacturerName: LUMI
    modelID: lumi.sensor_ht
    networkAddress: 20421
    type: EndDevice
  - definition:
      description: Mi/Aqara smart home cube
      model: MFKZQ01LM
      supports: >-
        battery, voltage, action_angle, action_from_side, action_side,
        action_to_side, action, linkquality
      vendor: Xiaomi
    friendlyName: cube
    ieeeAddr: '0x00158d00010b25fe'
    lastSeen: 1664971204447
    manufacturerName: LUMI
    modelID: lumi.sensor_cube.aqgl01
    networkAddress: 49799
    type: EndDevice
  - definition:
      description: MiJia temperature & humidity sensor
      model: WSDCGQ01LM
      supports: battery, temperature, humidity, voltage, linkquality
      vendor: Xiaomi
    friendlyName: chambre
    ieeeAddr: '0x00158d000408aea8'
    lastSeen: 1646490420047
    manufacturerName: LUMI
    modelID: lumi.sensor_ht
    networkAddress: 9221
    type: EndDevice
  - definition:
      description: MiJia temperature & humidity sensor
      model: WSDCGQ01LM
      supports: battery, temperature, humidity, voltage, linkquality
      vendor: Xiaomi
    friendlyName: garage
    ieeeAddr: '0x00158d000406c409'
    lastSeen: 1664972541371
    manufacturerName: LUMI
    modelID: lumi.sensor_ht
    networkAddress: 6791
    type: EndDevice
  - definition:
      description: Aqara door & window contact sensor
      model: MCCGQ11LM
      supports: battery, contact, temperature, voltage, linkquality
      vendor: Xiaomi
    friendlyName: porte
    ieeeAddr: '0x00158d0004470a44'
    lastSeen: 1664972687031
    manufacturerName: LUMI
    modelID: lumi.sensor_magnet.aq2
    networkAddress: 18
    type: EndDevice
  - definition:
      description: Aqara door & window contact sensor
      model: MCCGQ11LM
      supports: battery, contact, temperature, voltage, linkquality
      vendor: Xiaomi
    friendlyName: entrée
    ieeeAddr: '0x00158d00069ac6af'
    lastSeen: 1664971021585
    manufacturerName: LUMI
    modelID: lumi.sensor_magnet.aq2
    networkAddress: 22821
    type: EndDevice
  - definition:
      description: Motion sensor
      model: SNZB-03
      supports: occupancy, battery_low, tamper, battery, linkquality
      vendor: SONOFF
    friendlyName: détecteur_pir
    ieeeAddr: '0x00124b0025002a68'
    lastSeen: 1664257780225
    manufacturerName: eWeLink
    modelID: MS01
    networkAddress: 22193
    type: EndDevice
  - definition:
      description: Temperature & humidity sensor with display
      model: TS0201
      supports: battery, temperature, humidity, voltage, linkquality
      vendor: TuYa
    friendlyName: Chambre1
    ieeeAddr: '0xa4c138dda4142612'
    lastSeen: 1664972084908
    manufacturerName: _TZ3000_dowj6gyi
    modelID: TS0201
    networkAddress: 52330
    type: EndDevice
friendly_name: Zigbee2mqtt Networkmap

**Comment by azuwis** [comment]
Notice the `links: []` in the state attributes of `sensor.zigbee2mqtt_networkmap`, it's normal that the map shows no links in this case.

The state attributes is given by Zigbee2Mqtt，I think you should report the issue to upstream project https://github.com/Koenkk/zigbee2mqtt/issues

**Comment by Olive80** [comment]
I receive the informations for mqtt about quality link on home assistant 



![Screenshot_20221015-022635_Home Assistant](https://user-images.githubusercontent.com/58820544/195960626-9ecc3314-0403-4813-8a32-682b18d3682a.jpg)

**Comment by azuwis** [comment]
zigbee2mqtt-networkmap use this API https://www.zigbee2mqtt.io/guide/usage/mqtt_topics_and_messages.html#zigbee2mqtt-bridge-request to get information about the network map, including `nodes` and `links`, nodes are devices, links are how devices are connected. It's not just about linkquality.

According to the state attribute you posted, the zigbee2mqtt network map API gives `links: []`, which means no links, something is wrong about the API. It' up the upstream project Zigbee2MQTT to fix the problem.

**Comment by Olive80** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/11968
