### ISSUE TITLE
Using Home Assistant Name instead of Friendly Name in the map

### ISSUE THREAD

**Issue by kalon33** [azuwis/zigbee2mqtt-networkmap#50]
**Describe the bug**
Currently the map displays the friendly_name from Z2M, which is an hexadecimal string. It would be great to be able to use Home Assistant Name instead of the Friendly Name, as the latter is not that friendly when trying to identify a device.

**Home Assistant version**
2023.10.0

**Zigbee2mqtt version**
1.33.1

**OS and browser version**
Ubuntu 22.04.3 LTS

**Comment by azuwis** [comment]
See FAQ:

Q: How can I customize device names in the map?

A: The names showed in the map are given by Zigbee2mqtt, you need to configure Zigbee2mqtt to customize them, see https://www.zigbee2mqtt.io/guide/configuration/devices-groups.html#common-device-options for the friendly_name option.

Additionaly, HomeAssistant will automatically use the same names when MQTT auto discovery is enabled, see https://www.zigbee2mqtt.io/guide/usage/integrations/home_assistant.html#mqtt-discovery
