### ISSUE TITLE
Question building release 

### ISSUE THREAD

**Issue by sdotter** [azuwis/zigbee2mqtt-networkmap#51]
Hi! 

Awesome project!

Just wondering how to output a release...
If i do `yarn build` etc i get three files instead of one combined with all...
Hope you can help me out

Thanks! 👍👌

**Comment by azuwis** [comment]
`zigbee2mqtt-networkmap.js` is the release file, the other two are for the demo.

**Comment by sdotter** [comment]
Ohh ok thanks! i thought that too but my build output file gives an error like: 

<img width="427" alt="image" src="https://github.com/azuwis/zigbee2mqtt-networkmap/assets/11946839/d8f8dfea-778f-4cf9-b778-47aafec41b41">

<img width="343" alt="image" src="https://github.com/azuwis/zigbee2mqtt-networkmap/assets/11946839/f5a0e4cd-61b0-4b38-9bf3-7acb15c93547">

But it is working with your release v0.8.0 zigbee2mqtt-networkmap.js... 

I did:

`yarn install
yarn build`

<img width="377" alt="image" src="https://github.com/azuwis/zigbee2mqtt-networkmap/assets/11946839/e62933cf-d439-49fd-a360-df2a122b3ae8">

`$ yarn -v
1.22.21

$ node -v
v19.9.0

$ npm -v
9.6.3`

**Comment by sdotter** [comment]
It is breaking on this part:

`Vue.component('v-style', {
  render: function (createElement) {
    return createElement('style', this.$slots.default)
  }
})`

**Comment by sdotter** [comment]
Found the issue...

I needed to downgrade vue in package.json `"vue": "^2.7.14"`
Then when i build it works.

Still curious how your master/main branch can work...

Besides that awesome project from you! Thanks for sharing on github 👍👌

**Comment by azuwis** [comment]
Actually the master branch was not fully tested, it was a quick update for Nix packaging.

Thank for the investigation, fixed in 7851357d78ebc0d1cc3cb5c661267a1e8b4c09e3.
