### ISSUE TITLE
Post z2m v1.6.0 Edge versions problems

### ISSUE THREAD

**Issue by dreimer1986** [azuwis/zigbee2mqtt-networkmap#6]
Pics say more than thousand words here. I installed a new Edge version of zigbee2mqtt today to check if the now default zigbee-shepherd helps with some pairing issues and now this is the result: 
![2019-09-10 16_26_47-Window](https://user-images.githubusercontent.com/29841368/64622710-0c13ac00-d3e8-11e9-85ab-eb6b6c272c5e.png)

**Comment by azuwis** [comment]
The links are missing. Please paste the whole state attributes here. This is probably a Zigbee2mqtt problem, maybe the network map function is not ready.

**Comment by hajo62** [comment]
Since a few days I do see a similar picture and I assume I'm still on zigbee2mqtt 1.5.1

(Not sure how to check the docker container version or the networkmap version.)

**Comment by dreimer1986** [comment]
How do I get the state attributes?

**Comment by azuwis** [comment]
**Zigbee2mqtt version**
Check `zigbee2mqtt/package.json` file, e.g. `"version": "1.5.1"`.

**Error message on browser**
On Google Chrome, open browser `Menu` -> `More tools` -> `Developer tools` -> `Console`, and copy error message here if any.

**State attributes of `sensor.zigbee2mqtt_networkmap`**
On Home Assistant, go to `Menu` -> `Developer tools` -> `STATES` -> `sensor.zigbee2mqtt_networkmap`, and copy state attributes here.

Rgruebel' networkmap use MQTT topic `zigbee2mqtt/bridge/networkmap/graphviz` which give a Graphviz format data.

Mine use MQTT topic `zigbee2mqtt/bridge/networkmap/raw` which give JSON data.

They work in different ways.

Without the state attributes of `sensor.zigbee2mqtt_networkmap`, I won't be able to debug the problem.

**Comment by azuwis** [comment]
I need the JSON text, click the link `sensor.zigbee2mqtt_networkmap` at the left and scroll up.

Copy the text here, image won't help.

![img](https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/original/3X/6/1/61dea7087ebd33ba4d1e09fdfdc593cecebd97fb.png)

**Comment by dreimer1986** [comment]
OK, this will be quite some text:

States of the sensor:

´´´
nodes
[object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object]
links
[object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object]
´´´

Console output:
https://www.pastiebin.com/5d7f389276df6 All these come when I open the site. Except the Access violations at the end.

Anything else needed? I even can provide you access if you wanna tinker a bit

**Comment by azuwis** [comment]
According to the sensor attributes posted, it seems the `zigbee2mqtt/bridge/networkmap/raw` API of Zigbee2mqtt v1.6.0 was changed.

Zigbee2mqtt v1.5.1 give links JSON like this:
``` json
    {
      "sourceIeeeAddr": "0x000b57fffe32dd9a",
      "targetIeeeAddr": "0x00124b0018ed250c",
      "sourceNwkAddr": 36307,
      "lqi": 0,
      "depth": 255,
      "relationship": 3,
      "routes": []
    }
```

Zigbee2mqtt v1.6.0 give links JSON like this:
``` json
    {
      "source": {
        "ieeeAddr": "0x90fd9ffffeee79a7",
        "networkAddress": 6986
      },
      "target": {
        "ieeeAddr": "0x000b57fffe4c8e1e",
        "networkAddress": 56090
      },
      "linkquality": 212,
      "depth": 15,
      "routes": []
    }
```

Unfortunately I can not test Zigbee2mqtt v1.6.0 myself due to hard disk failure of my NUC.

@Koenkk Can you confirm this? If the API is final, I need update the code accordingly.

**Comment by Koenkk** [comment]
@azuwis that is indeed the new API, but as zigbee2mqtt 1.7 will be a minor release it shouldn't contain breaking changes.

Note that this is NOT a zigbee2mqtt 1.6 issue but an issue with zigbee2mqtt 1.6 dev. I fixed the breaking change so it should work again now.

**Comment by dreimer1986** [comment]
Confirmed working again! Thx at both for the help ^^
![2019-09-18 08_36_14-Home Assistant](https://user-images.githubusercontent.com/29841368/65121413-71baf600-d9ef-11e9-94f6-0196e4337960.png)
