### ISSUE TITLE
The map is empty

### ISSUE THREAD

**Issue by Gooman-rus** [azuwis/zigbee2mqtt-networkmap#7]
**Describe the bug**
In zigbee2mqtt I have logs after I click REFRESH button:

>  zigbee2mqtt:info 9/14/2019, 5:03:39 PM MQTT publish: topic 'zigbee2mqtt/bridge/networkmap/raw', payload  

But there is no graph on the screen.
**Screenshots**
![image](https://user-images.githubusercontent.com/3216521/64909178-72167100-d711-11e9-845c-0cb7b70eac3f.png)

**Home Assistant version**
0.98.5

**Zigbee2mqtt version**
1.4.0

**OS and browser version**
Windows 10, Chrome 76.0.3809.132

**Error message on browser**
No errors in console.

**State attributes of `sensor.zigbee2mqtt_networkmap`**
On Home Assistant, go to `Menu` -> `Developer tools` -> `STATES` -> `sensor.zigbee2mqtt_networkmap`, 
```
2019-09-14 17:03:39
```

**Additional context**
When I click REFRESH button, after refreshing, I receive this message in hassio logs:
![image](https://user-images.githubusercontent.com/3216521/64909227-fd900200-d711-11e9-8675-671ccd41c1d0.png)

**Comment by azuwis** [comment]
Please update Zigbee2mqtt to version 1.5.1 and try again.

**Comment by azuwis** [comment]
Closing due to lack of response. Feel free to reopen if problem is not resolved.

**Comment by PrzemekSkw** [comment]
Hello @azuwis I also have problem with empty map card.
![Zrzut ekranu z 2021-12-13 12-25-23](https://user-images.githubusercontent.com/25219988/145804244-8a72446d-9fd2-4d85-8c6a-2be227766917.png)

I install zigbee network card in HACS. I add that entry to my configuration.yaml:
```
- platform: mqtt
    name: Zigbee2mqtt Networkmap
    # if you change base_topic of Zigbee2mqtt, change state_topic accordingly
    state_topic: zigbee2mqtt/bridge/networkmap/raw
    value_template: >-
      {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
    # again, if you change base_topic of Zigbee2mqtt, change json_attributes_topic accordingly
    json_attributes_topic: zigbee2mqtt/bridge/networkmap/raw
```
I see that my `sensor.zigbee2mqtt_networkmap` don't have ID in entities register tab.
In logs I see:
```
Logger: frontend.js.latest.202112120
Source: components/system_log/__init__.py:189
First occurred: 12:04:38 (4 occurrences)
Last logged: 12:24:10

https://homeassistant.ddns.net/lovelace/0?homescreen=1:0:0 Uncaught
https://homeassistant.ddns.net/lovelace/0:0:0 Uncaught
https://homeassistant.ddns.net/config/lovelace/resources:0:0 Uncaught
https://homeassistant.ddns.net/lovelace/zigbee-network:0:0 Uncaught
```
I have cc2652p zigbee usb stick connected to MiniPC (Dietpi - Debian 11, HA core version). I install zigbee2mqtt with docker like in zigbee2mqtt official guide. I update docker today. I have MQTT integration in HA. I don't install zigbee integration. Can I use Your Map in my config?

Regards,
Przemek

**Comment by Gooman-rus** [comment]
@PrzemekSkw tries to use this old networkmap plugin, so his configuration.yaml refers to this plugin, not to the zigbee2mqtt addon. I also can recommend to use zigbee2mqtt addon to see the map because it works great and you won't need to do additional actions. 
You can go to the UI representation of the zigbee2mqtt addon and then click "Map" on the horizontal menu. After that click "Load map" button and after some seconds or minutes the map will appear.

**Comment by PrzemekSkw** [comment]
Dear @azuwis I follow that guide and copy that code to my configuration.yaml file so if that is incorect I don't know what to do.

Hi, @Gooman-rus what do You mean zigbee2mqtt addon? I don't have Hassio so I don't see any addon in official integrations or HACS. I see only official `Zigbee Home Automation` integration.

Regards.

**Comment by Gooman-rus** [comment]
If you use official `Zigbee Home Automation` from HomeAssistant than you can't use this addon `zigbee2mqtt-networkmap`
 because:

1. It's very old and it is not supported anymore as I can see.
2. It was created particularly for **zigbee2mqtt** HomeAssistant addon.

**Comment by PrzemekSkw** [comment]
So if I don't have Hassio I can't install that map?

**Comment by Gooman-rus** [comment]
You can't use that map because it does not support Zigbee Home Automation integration.

**Comment by PrzemekSkw** [comment]
OK, but I don't use that addon. I have only MQTT integration in HA to discover my zigbee devices. I have zigbee2mqtt installed as docker.

**Comment by Gooman-rus** [comment]
If you have zigbee2mqtt container installed than you can access web page of zigbee2mqtt. There you can find Map option in the menu. Please [see this](https://www.zigbee2mqtt.io/guide/configuration/frontend.html) in order to access frontend.

**Comment by PrzemekSkw** [comment]
Thank You very much. I don't know there's a dashboard :)

Regards.

**Comment by PrzemekSkw** [comment]
I try that but don't work, meybe You know how to fix that: [https://github.com/nurikk/zigbee2mqtt-frontend/issues/1171](url)
?
