### ISSUE TITLE
Please add this to HACS

### ISSUE THREAD

**Issue by mikeage** [azuwis/zigbee2mqtt-networkmap#8]
**Describe the bug**
HACS has emerged as the de facto standard for custom cards and components; is it possible to add this to HACS? See the documentation at https://hacs.netlify.com/docs/publish/start 

**Screenshots**
n/a

**Home Assistant version**
n/a

**Zigbee2mqtt version**
n/a

**OS and browser version**
n/a

**Error message on browser**
n/a

**State attributes of `sensor.zigbee2mqtt_networkmap`**
n/a

**Home Assistant log**
n/a

**Additional context**
n/a

**Comment by azuwis** [comment]
Done, see https://github.com/custom-components/hacs/pull/711

Can you please test it? I don't use HACS myself.

**Comment by mikeage** [comment]
Looks good. Thanks!

**Comment by james-fry** [comment]
Great - thanks for this!
